import type { AssessmentDefinition } from "./types";

const likert5 = [1,2,3,4,5].map((n) => ({ value: String(n), label: String(n), score: n }));
const yesNo = [{ value: "yes", label: "Ya" }, { value: "no", label: "Belum/Tidak" }];
const multi = (values: string[]) => values.map((label, index) => ({ value: `o${index + 1}`, label }));

export const learningAssessmentV1: AssessmentDefinition = {
  slug: "belajar",
  version: 1,
  domain: "learning",
  title: "Asesmen Bimbingan Belajar",
  subtitle: "Masalah Belajar • Penyebab • Dampak • Kebutuhan & Aksi",
  intro: "Asesmen ini membantu siswa dan Guru BK memahami kondisi belajar secara lebih mendalam. Hasilnya bukan label rajin atau malas, melainkan bahan refleksi untuk menentukan dukungan yang paling dibutuhkan.",
  sections: [
    {
      id: "initial_map",
      title: "B. Pemetaan Awal Masalah Belajar",
      description: "Pilih semua masalah yang sedang Anda alami, lalu tentukan tiga masalah yang paling mengganggu.",
      items: [
        { id: "learning_subject", prompt: "Mata pelajaran yang paling menjadi perhatian", type: "text" },
        { id: "learning_problem_areas", prompt: "Area masalah belajar yang sedang saya alami", type: "multi", options: multi([
          "Motivasi — Sulit memulai belajar, tidak melihat tujuan, cepat menyerah.",
          "Konsentrasi — Mudah terdistraksi, pikiran melayang, sulit bertahan fokus.",
          "Manajemen waktu — Jadwal berantakan, tugas menumpuk, sulit menentukan prioritas.",
          "Prokrastinasi — Sering menunda walaupun mengetahui tugas harus dikerjakan.",
          "Pemahaman materi — Sudah belajar tetapi materi tetap sulit dipahami.",
          "Kebiasaan belajar — Belajar tidak teratur, hanya saat ada ujian atau tugas.",
          "Tugas sekolah — Sering terlambat, lupa, tidak selesai, atau kewalahan.",
          "Ujian & evaluasi — Cemas, blank, sulit mengatur waktu, hasil tidak sesuai persiapan.",
          "Nilai akademik — Nilai turun, stagnan, atau jauh dari target.",
          "Gadget & media sosial — HP/game/media sosial sering mengambil waktu belajar.",
          "Kelelahan & tidur — Mengantuk, sulit bangun, energi rendah ketika belajar.",
          "Tekanan akademik — Takut gagal, takut mengecewakan orang tua/guru, terlalu membandingkan diri.",
          "Lingkungan belajar — Tempat belajar bising, tidak nyaman, atau banyak gangguan.",
          "Kegiatan sekolah/organisasi — Sulit menyeimbangkan belajar dengan kegiatan lain.",
          "Dukungan belajar — Bingung meminta bantuan atau tidak tahu harus bertanya kepada siapa.",
        ]) },
        { id: "top_problem_1", prompt: "Masalah utama 1", type: "text" },
        { id: "top_problem_2", prompt: "Masalah utama 2", type: "text" },
        { id: "top_problem_3", prompt: "Masalah utama 3", type: "text" },
      ],
    },
    {
      id: "problem",
      title: "C. Pilar 1 — Apa Masalah Belajar Saya?",
      description: "Masalah belajar apa yang paling mengganggu saya saat ini, dan bagaimana bentuknya dalam kegiatan sehari-hari?",
      items: [
        { id: "problem_main", prompt: "1. Apa masalah utama yang paling ingin saya perbaiki?", type: "textarea" },
        { id: "problem_when", prompt: "2. Kapan masalah ini paling sering muncul?", type: "textarea" },
        { id: "problem_subject", prompt: "3. Mata pelajaran atau situasi apa yang paling terdampak?", type: "textarea" },
        { id: "problem_frequency", prompt: "4. Seberapa sering masalah ini terjadi?", type: "textarea" },
        { id: "problem_duration", prompt: "5. Apakah masalah ini baru terjadi atau sudah berlangsung lama?", type: "textarea" },
        { id: "problem_example", prompt: "6. Apa contoh kejadian terbaru yang menunjukkan masalah tersebut?", type: "textarea" },
        { id: "problem_disruption", prompt: "Skala gangguan", type: "likert", options: [
          {value:"1",label:"1 · Sangat ringan",score:1},{value:"2",label:"2 · Ringan",score:2},{value:"3",label:"3 · Sedang",score:3},{value:"4",label:"4 · Berat",score:4},{value:"5",label:"5 · Sangat berat",score:5},
        ] },
      ],
    },
    {
      id: "cause",
      title: "D. Pilar 2 — Kenapa Masalah Belajar Ini Terjadi?",
      description: "Apa penyebab utama yang membuat saya sulit belajar secara optimal? Jangan berhenti pada ‘malas’; cari faktor yang lebih spesifik.",
      items: [
        { id: "cause_options", prompt: "Kemungkinan penyebab", type: "multi", options: multi([
          "Strategi belajar — Cara belajar belum sesuai kebutuhan materi; terlalu banyak membaca pasif; kurang latihan.",
          "Pemahaman dasar — Ada konsep prasyarat yang belum dikuasai.",
          "Motivasi & tujuan — Belum memahami alasan belajar atau target terasa tidak bermakna.",
          "Manajemen waktu — Tidak ada prioritas; waktu banyak habis untuk aktivitas lain.",
          "Gadget & distraksi — Notifikasi, media sosial, game, video, atau chat mengganggu fokus.",
          "Kondisi fisik — Kurang tidur, lelah, lapar, sakit, atau ritme harian tidak teratur.",
          "Kondisi emosi — Cemas, kecewa, konflik, tekanan, atau pikiran lain mengganggu belajar.",
          "Lingkungan — Tempat belajar bising, ramai, tidak nyaman, atau tidak mendukung.",
          "Beban kegiatan — Tugas, organisasi, ekstrakurikuler, atau aktivitas keluarga terlalu padat.",
          "Kesulitan meminta bantuan — Takut bertanya, malu, atau tidak tahu sumber bantuan.",
        ]) },
        { id: "cause_main", prompt: "Menurut saya, penyebab paling besar adalah:", type: "textarea" },
        { id: "cause_evidence", prompt: "Bukti atau contoh yang membuat saya berpikir demikian:", type: "textarea" },
        { id: "cause_self", prompt: "Faktor mana yang bisa saya ubah sendiri?", type: "textarea" },
        { id: "cause_help", prompt: "Faktor mana yang membutuhkan bantuan orang lain?", type: "textarea" },
      ],
    },
    {
      id: "impact",
      title: "E. Pilar 3 — Apa Dampaknya Jika Dibiarkan?",
      description: "Apa akibat masalah belajar ini terhadap nilai, kebiasaan, emosi, hubungan, dan masa depan akademik saya?",
      items: [
        { id: "impact_areas", prompt: "Area dampak yang terjadi", type: "multi", options: multi([
          "Akademik — Nilai turun, tugas tertinggal, pemahaman makin lemah.",
          "Kebiasaan — Semakin sering menunda dan belajar hanya ketika terdesak.",
          "Emosi — Cemas, kecewa, frustrasi, minder, atau takut menghadapi pelajaran.",
          "Fisik — Kurang tidur, kelelahan, sulit menjaga rutinitas.",
          "Hubungan — Konflik dengan orang tua/guru karena tugas atau nilai.",
          "Masa depan — Pilihan jurusan/karier menjadi lebih terbatas jika kompetensi penting tidak dibangun.",
        ]) },
        { id: "impact_now", prompt: "Dampak yang paling saya rasakan saat ini:", type: "textarea" },
        { id: "impact_3m", prompt: "Jika tidak diperbaiki dalam 3 bulan, apa yang saya khawatirkan akan terjadi?", type: "textarea" },
        { id: "impact_change", prompt: "Apa yang akan berubah jika masalah ini berhasil saya atasi?", type: "textarea" },
      ],
    },
    {
      id: "needs",
      title: "F. Pilar 4 — Apa yang Saya Butuhkan agar Belajar Lebih Baik?",
      description: "Dukungan, kebiasaan, strategi, lingkungan, dan kemampuan apa yang perlu saya bangun untuk memperbaiki proses belajar?",
      items: [
        { id: "need_options", prompt: "Kebutuhan saya", type: "multi", options: multi([
          "Target yang jelas — Menentukan sasaran mingguan yang spesifik dan realistis.",
          "Jadwal belajar — Membuat waktu belajar yang konsisten dan tidak terlalu padat.",
          "Strategi belajar aktif — Latihan soal, active recall, membuat rangkuman sendiri, menjelaskan kembali materi.",
          "Kontrol gadget — Membatasi notifikasi, menetapkan waktu akses, dan menjauhkan HP saat sesi fokus.",
          "Perbaikan tidur — Menjaga jam tidur agar fokus dan energi belajar lebih baik.",
          "Bantuan akademik — Bertanya kepada guru, teman, tutor, atau menggunakan sumber belajar yang tepat.",
          "Lingkungan belajar — Mencari tempat yang lebih tenang, rapi, terang, dan minim distraksi.",
          "Dukungan emosional — Berbicara dengan Guru BK/orang tua ketika tekanan akademik terasa berat.",
          "Penguatan niat & disiplin — Menghubungkan belajar dengan tanggung jawab, tujuan hidup, dan kebermanfaatan.",
        ]) },
        { id: "need_priority_1", prompt: "Kebutuhan prioritas 1", type: "text" },
        { id: "need_priority_2", prompt: "Kebutuhan prioritas 2", type: "text" },
        { id: "need_priority_3", prompt: "Kebutuhan prioritas 3", type: "text" },
      ],
    },
    {
      id: "habits",
      title: "G. Cek Kebiasaan Belajar",
      description: "Skala: 1 = Tidak Pernah | 2 = Jarang | 3 = Kadang-kadang | 4 = Sering | 5 = Sangat Sering. Total skor /50 digunakan sebagai refleksi, bukan diagnosis.",
      items: [
        "Saya memiliki waktu belajar yang relatif tetap.",
        "Saya menentukan target sebelum mulai belajar.",
        "Saya dapat memulai belajar tanpa harus selalu diingatkan.",
        "Saya menyelesaikan tugas sebelum mendekati batas waktu.",
        "Saya mematikan atau membatasi notifikasi saat belajar.",
        "Saya menggunakan latihan aktif, bukan hanya membaca ulang.",
        "Saya mengevaluasi kesalahan setelah mengerjakan soal.",
        "Saya bertanya ketika benar-benar tidak memahami materi.",
        "Saya menjaga tidur agar cukup pada hari sekolah.",
        "Saya mampu membagi waktu antara belajar, ibadah, keluarga, dan kegiatan lain.",
      ].map((prompt, index) => ({ id: `habit_${index+1}`, prompt, type: "likert" as const, options: likert5 })),
    },
    {
      id: "motivation",
      title: "H. Cek Motivasi & Tujuan Belajar",
      items: [
        { id: "motivation_1", prompt: "Apa alasan terbesar saya belajar saat ini?", type: "textarea" },
        { id: "motivation_2", prompt: "Apakah tujuan belajar saya berasal dari diri sendiri, orang tua, guru, atau tekanan teman?", type: "textarea" },
        { id: "motivation_3", prompt: "Apa hubungan pelajaran yang saya jalani dengan cita-cita atau masa depan saya?", type: "textarea" },
        { id: "motivation_4", prompt: "Apa hal yang membuat saya merasa semangat ketika belajar?", type: "textarea" },
        { id: "motivation_5", prompt: "Apa hal yang paling cepat membuat saya kehilangan semangat?", type: "textarea" },
        { id: "motivation_6", prompt: "Ketika nilai saya tidak sesuai harapan, biasanya saya melakukan apa?", type: "textarea" },
        { id: "motivation_7", prompt: "Jika saya boleh memperbaiki satu hal tentang kebiasaan belajar saya, apa yang akan saya pilih?", type: "textarea" },
      ],
    },
    {
      id: "gadget",
      title: "I. Cek Konsentrasi & Gadget",
      description: "Skala: 1 = Tidak Pernah | 2 = Jarang | 3 = Kadang-kadang | 4 = Sering | 5 = Sangat Sering.",
      items: [
        ...[
          "Saya membuka HP ketika sedang belajar meskipun tidak diperlukan.",
          "Saya sulit kembali fokus setelah membuka media sosial atau chat.",
          "Saya belajar sambil menonton video/streaming yang tidak terkait pelajaran.",
          "Saya sering menunda belajar karena game atau media sosial.",
          "Saya menggunakan HP sampai larut malam sehingga mengantuk keesokan harinya.",
          "Saya dapat menjalani sesi fokus 25–40 menit tanpa gangguan digital.",
        ].map((prompt, index) => ({ id: `gadget_${index+1}`, prompt, type: "likert" as const, options: likert5 })),
        { id: "digital_strategy", prompt: "Strategi digital yang akan saya coba minggu ini", type: "multi", options: multi([
          "Mode jangan ganggu saat belajar", "HP diletakkan di luar jangkauan", "Batas waktu media sosial/game", "Tidak membawa HP saat sesi fokus tertentu", "Menghapus notifikasi yang tidak penting",
        ]) },
        { id: "digital_strategy_other", prompt: "Lainnya", type: "text" },
      ],
    },
    {
      id: "tasks_exams_grades",
      title: "J. Cek Tugas, Ujian, dan Nilai",
      description: "Skala: 1 = Tidak Pernah | 2 = Jarang | 3 = Kadang-kadang | 4 = Sering | 5 = Sangat Sering.",
      items: [
        "Saya sering menumpuk tugas sampai mendekati deadline.",
        "Saya memahami instruksi tugas sebelum mulai mengerjakan.",
        "Saya memecah tugas besar menjadi langkah kecil.",
        "Saya mulai belajar cukup jauh sebelum ujian.",
        "Saya sering blank atau panik ketika ujian.",
        "Saya mengevaluasi kesalahan setelah ujian.",
        "Saya memahami alasan nilai saya naik atau turun.",
        "Saya punya target nilai yang realistis.",
        "Saya fokus pada perbaikan proses, bukan hanya membandingkan diri dengan teman.",
      ].map((prompt, index) => ({ id: `academic_check_${index+1}`, prompt, type: "likert" as const, options: likert5 })),
    },
    {
      id: "pressure",
      title: "K. Cek Tekanan Akademik & Kebutuhan Dukungan",
      description: "Jika tekanan belajar membuat Anda tidak mampu menjalani aktivitas sehari-hari, merasa sangat putus asa, mengalami perundungan, atau merasa tidak aman, hasil perlu segera ditindaklanjuti secara pribadi oleh Guru BK.",
      items: [
        { id: "pressure_1", prompt: "Saya merasa terlalu takut gagal.", type: "yes_no", options: yesNo },
        { id: "pressure_2", prompt: "Saya merasa nilai menentukan harga diri saya.", type: "yes_no", options: yesNo },
        { id: "pressure_3", prompt: "Saya sering takut mengecewakan orang tua atau guru.", type: "yes_no", options: yesNo },
        { id: "pressure_4", prompt: "Saya sangat cemas menjelang ujian atau pengumpulan tugas.", type: "yes_no", options: yesNo },
        { id: "pressure_5", prompt: "Saya sulit tidur karena memikirkan pelajaran atau nilai.", type: "yes_no", options: yesNo },
        { id: "pressure_6", prompt: "Saya merasa kewalahan karena terlalu banyak tuntutan sekaligus.", type: "yes_no", options: yesNo },
        { id: "pressure_bk", prompt: "Saya ingin berbicara secara pribadi dengan Guru BK mengenai tekanan belajar saya.", type: "yes_no", sensitive: true, options: [{value:"yes",label:"Ya",signal:{kind:"learning_help_request",severity:"attention",private:true}},{value:"no",label:"Belum/Tidak"}] },
      ],
    },
    {
      id: "action_plan",
      title: "L. Learning Action Plan — Rencana Perbaikan 14 Hari",
      description: "Pilih sedikit target tetapi jelas. Rencana yang baik dapat dilakukan, diukur, dan dievaluasi.",
      items: [
        { id: "learning_plan_target", prompt: "Target", type: "text" },
        { id: "learning_plan_step", prompt: "Langkah kecil", type: "textarea" },
        { id: "learning_plan_when", prompt: "Kapan", type: "text" },
        { id: "learning_plan_evidence", prompt: "Bukti selesai", type: "text" },
        { id: "learning_plan_support", prompt: "Dukungan", type: "text" },
        { id: "learning_plan_commitment", prompt: "Komitmen utama saya", type: "textarea" },
        { id: "learning_plan_reward", prompt: "Hadiah sehat jika saya konsisten", type: "textarea" },
        { id: "learning_plan_reset", prompt: "Yang akan saya lakukan jika gagal satu hari", type: "textarea" },
      ],
    },
    {
      id: "weekly_reflection",
      title: "M. Refleksi Mingguan Siswa",
      items: [
        { id: "weekly_success", prompt: "Apa yang berhasil saya lakukan minggu ini?", type: "textarea" },
        { id: "weekly_barrier", prompt: "Apa hambatan terbesar saya?", type: "textarea" },
        { id: "weekly_focus_time", prompt: "Kapan saya paling fokus belajar?", type: "textarea" },
        { id: "weekly_distraction", prompt: "Apa distraksi terbesar saya?", type: "textarea" },
        { id: "weekly_subject_growth", prompt: "Mata pelajaran apa yang paling berkembang?", type: "textarea" },
        { id: "weekly_strategy", prompt: "Apakah strategi yang saya gunakan efektif? Mengapa?", type: "textarea" },
        { id: "weekly_change", prompt: "Apa satu perubahan yang akan saya lakukan minggu depan?", type: "textarea" },
        ...["Fokus","Disiplin waktu","Penyelesaian tugas","Motivasi","Kontrol gadget","Kualitas tidur"].map((prompt,index)=>({id:`weekly_scale_${index+1}`,prompt,type:"likert" as const,options:likert5})),
      ],
    },
  ],
};
