import type { AssessmentDefinition } from "./types";

const likert5 = [1,2,3,4,5].map((n) => ({ value: String(n), label: String(n), score: n }));
const yesNo = [{ value: "yes", label: "Ya" }, { value: "no", label: "Tidak" }];
const multi = (values: string[]) => values.map((label, index) => ({ value: `o${index + 1}`, label }));

export const personalAssessmentV1: AssessmentDefinition = {
  slug: "pribadi",
  version: 1,
  domain: "personal",
  title: "Asesmen Kebutuhan Bimbingan Pribadi",
  subtitle: "Kenali Diri • Kelola Emosi • Bangun Kebiasaan • Tumbuh dengan Nilai",
  intro: "Asesmen ini membantu siswa mengenali kebutuhan pribadi yang sedang mengganggu kenyamanan, perkembangan, ibadah, relasi, atau proses belajar. Hasil asesmen bukan label kepribadian dan bukan diagnosis klinis.",
  sections: [
    {
      id: "checkin",
      title: "C. Check-in Kondisi Pribadi",
      description: "Pilih jawaban yang paling menggambarkan kondisi Anda selama beberapa minggu terakhir. Keterangan: 1 = sangat tidak sesuai, 5 = sangat sesuai.",
      items: [
        { id: "checkin_1", prompt: "Saya merasa cukup mengenal kekuatan dan kelemahan diri saya.", type: "likert", options: likert5, required: true },
        { id: "checkin_2", prompt: "Saya cukup percaya diri dalam menjalani aktivitas sekolah.", type: "likert", options: likert5, required: true },
        { id: "checkin_3", prompt: "Saya dapat mengelola emosi ketika marah, sedih, kecewa, atau takut.", type: "likert", options: likert5, required: true },
        { id: "checkin_4", prompt: "Saya mampu mengendalikan kebiasaan yang mengganggu diri saya.", type: "likert", options: likert5, required: true },
        { id: "checkin_5", prompt: "Saya merasa memiliki tempat yang aman untuk bercerita.", type: "likert", options: likert5, required: true },
        { id: "checkin_6", prompt: "Saya merasa kehidupan sehari-hari saya cukup teratur.", type: "likert", options: likert5, required: true },
        { id: "checkin_7", prompt: "Saya memiliki tujuan pribadi yang ingin saya capai.", type: "likert", options: likert5, required: true },
        { id: "checkin_8", prompt: "Saya merasa nilai-nilai agama membantu saya mengambil keputusan dengan lebih baik.", type: "likert", options: likert5, required: true },
      ],
    },
    {
      id: "self_confidence",
      title: "1. Mengenal Diri dan Kepercayaan Diri",
      description: "Fokus: penerimaan diri, kelebihan-kekurangan, keberanian tampil, serta cara memandang diri sendiri.",
      items: [
        { id: "self_confidence_flags", prompt: "Pilih semua yang sesuai dengan kondisi Anda.", type: "multi", options: multi([
          "Saya sering merasa tidak cukup baik dibanding orang lain.",
          "Saya sulit melihat kelebihan yang saya miliki.",
          "Saya takut salah atau takut dinilai ketika harus tampil.",
          "Saya sering membandingkan diri dengan teman atau orang di media sosial.",
          "Saya merasa minder dengan kemampuan akademik saya.",
          "Saya kurang nyaman dengan penampilan atau kondisi fisik saya.",
          "Saya sulit menerima kritik tanpa merasa sangat terpukul.",
          "Saya merasa pendapat saya kurang berharga.",
          "Saya bingung dengan diri saya dan belum tahu ingin berkembang menjadi seperti apa.",
        ]) },
        { id: "self_confidence_other", prompt: "Lainnya", type: "text" },
        { id: "self_confidence_q1", prompt: "Hal apa dari diri saya yang paling sering membuat saya tidak percaya diri?", type: "textarea" },
        { id: "self_confidence_q2", prompt: "Situasi apa yang paling memicu rasa minder, malu, atau takut dinilai?", type: "textarea" },
        { id: "self_confidence_q3", prompt: "Apa kelebihan saya yang sebenarnya sudah terlihat tetapi jarang saya hargai?", type: "textarea" },
        { id: "self_confidence_q4", prompt: "Apa bantuan yang paling saya butuhkan agar lebih percaya diri?", type: "textarea" },
      ],
    },
    {
      id: "emotion",
      title: "2. Emosi, Stres, dan Ketenangan Diri",
      description: "Fokus: mengenali emosi, pemicu, cara menenangkan diri, dan dampaknya terhadap keseharian.",
      items: [
        { id: "emotion_flags", prompt: "Pilih semua yang sesuai dengan kondisi Anda.", type: "multi", options: multi([
          "Saya mudah marah atau tersinggung.",
          "Saya sering merasa sedih tanpa tahu harus bercerita kepada siapa.",
          "Saya sering merasa cemas atau takut berlebihan tentang sesuatu.",
          "Saya sulit tenang ketika ada masalah.",
          "Saya menyimpan masalah sendiri sampai terasa berat.",
          "Saya mudah menangis atau kehilangan semangat ketika gagal.",
          "Saya sulit tidur karena banyak pikiran.",
          "Saya sering merasa lelah secara emosional.",
          "Saya sulit memaafkan diri sendiri ketika melakukan kesalahan.",
          "Saya sering merasa kewalahan dengan banyak tuntutan.",
        ]) },
        { id: "emotion_q1", prompt: "Emosi yang paling sering saya rasakan akhir-akhir ini:", type: "textarea" },
        { id: "emotion_q2", prompt: "Apa pemicu yang biasanya membuat emosi tersebut muncul?", type: "textarea" },
        { id: "emotion_q3", prompt: "Apa yang biasanya saya lakukan ketika emosi itu muncul?", type: "textarea" },
        { id: "emotion_q4", prompt: "Apakah cara tersebut membantu atau justru membuat masalah bertambah? Jelaskan.", type: "textarea" },
      ],
    },
    {
      id: "self_control",
      title: "3. Kontrol Diri dan Kebiasaan",
      description: "Fokus: disiplin pribadi, penggunaan gadget, tidur, menunda, impuls, dan kebiasaan yang ingin diperbaiki.",
      items: [
        { id: "self_control_flags", prompt: "Pilih semua yang sesuai dengan kondisi Anda.", type: "multi", options: multi([
          "Saya sulit berhenti menggunakan HP/media sosial meskipun sudah berniat.",
          "Saya sering tidur terlalu larut.",
          "Saya sering menunda hal penting sampai mendekati batas waktu.",
          "Saya mudah terbawa keinginan sesaat lalu menyesal.",
          "Saya sulit mempertahankan kebiasaan baik secara konsisten.",
          "Saya mudah kehilangan fokus pada target yang sudah dibuat.",
          "Saya memiliki kebiasaan yang ingin dihentikan tetapi belum berhasil.",
          "Saya sering merasa bersalah setelah melakukan sesuatu secara impulsif.",
          "Saya sulit membuat batas antara waktu belajar, hiburan, dan istirahat.",
          "Saya ingin menjadi lebih disiplin tetapi belum tahu caranya.",
        ]) },
        { id: "self_control_q1", prompt: "Kebiasaan yang paling ingin saya perbaiki:", type: "textarea" },
        { id: "self_control_q2", prompt: "Kapan kebiasaan itu paling sering muncul?", type: "textarea" },
        { id: "self_control_q3", prompt: "Apa pemicu utamanya?", type: "textarea" },
        { id: "self_control_q4", prompt: "Apa kebiasaan pengganti yang lebih sehat/bermanfaat yang mungkin saya lakukan?", type: "textarea" },
      ],
    },
    {
      id: "family",
      title: "4. Kondisi Rumah dan Keluarga",
      description: "Fokus: hal pribadi di rumah yang memengaruhi emosi, rasa aman, belajar, atau perkembangan diri. Siswa tidak wajib menuliskan detail yang membuat tidak nyaman.",
      items: [
        { id: "family_flags", prompt: "Pilih semua yang sesuai dengan kondisi Anda.", type: "multi", sensitive: true, options: multi([
          "Saya merasa sulit berkomunikasi dengan orang tua/wali.",
          "Saya merasa terlalu banyak tuntutan di rumah.",
          "Saya sering merasa tidak dipahami oleh keluarga.",
          "Ada konflik keluarga yang ikut mengganggu pikiran saya.",
          "Saya merasa dibanding-bandingkan dengan saudara atau orang lain.",
          "Saya merasa kurang mendapat dukungan untuk hal yang penting bagi saya.",
          "Saya memiliki tanggung jawab di rumah yang cukup berat.",
          "Kondisi rumah kadang membuat saya sulit belajar atau beristirahat.",
          "Saya ingin membicarakan sesuatu tentang keluarga secara pribadi dengan Guru BK.",
          "Saya tidak memiliki masalah berarti di area ini.",
        ]) },
        { id: "family_q1", prompt: "Hal di rumah yang paling memengaruhi kondisi saya saat ini (boleh singkat):", type: "textarea", sensitive: true },
        { id: "family_q2", prompt: "Dampaknya terhadap saya:", type: "textarea", sensitive: true },
        { id: "family_q3", prompt: "Bantuan atau dukungan yang saya harapkan:", type: "textarea", sensitive: true },
      ],
    },
    {
      id: "decision",
      title: "5. Pengambilan Keputusan dan Tujuan Pribadi",
      description: "Fokus: kemampuan memilih, menentukan prioritas, menetapkan batas, dan memiliki arah perkembangan diri.",
      items: [
        { id: "decision_flags", prompt: "Pilih semua yang sesuai dengan kondisi Anda.", type: "multi", options: multi([
          "Saya sering bingung mengambil keputusan meskipun pilihan sudah jelas.",
          "Saya mudah mengikuti orang lain agar tidak dianggap berbeda.",
          "Saya sulit mengatakan “tidak” ketika sebenarnya tidak nyaman.",
          "Saya sering menyesali keputusan karena dibuat terlalu cepat.",
          "Saya belum memiliki tujuan pribadi yang jelas.",
          "Saya punya target tetapi sulit memecahnya menjadi langkah kecil.",
          "Saya sulit membedakan keinginan sendiri dengan tekanan dari orang lain.",
          "Saya takut salah memilih sehingga akhirnya tidak memilih apa pun.",
        ]) },
        { id: "decision_q1", prompt: "Keputusan yang sedang sulit saya ambil:", type: "textarea" },
        { id: "decision_q2", prompt: "Pilihan yang tersedia saat ini:", type: "textarea" },
        { id: "decision_q3", prompt: "Nilai apa yang penting untuk saya pertimbangkan sebelum memilih?", type: "textarea" },
        { id: "decision_q4", prompt: "Siapa orang dewasa yang bisa saya ajak berdiskusi secara sehat?", type: "textarea" },
      ],
    },
    {
      id: "values",
      title: "6. Nilai Diri, Ibadah, dan Makna",
      description: "Fokus: bagaimana nilai Islam membantu siswa menjaga arah, tanggung jawab, harapan, dan keseimbangan diri tanpa menjadikan kesulitan pribadi sebagai ukuran kualitas iman.",
      items: [
        { id: "values_flags", prompt: "Pilih semua yang sesuai dengan kebutuhan Anda.", type: "multi", options: multi([
          "Saya ingin memperbaiki niat dan tujuan dalam aktivitas sehari-hari.",
          "Saya ingin lebih konsisten menjalankan kewajiban dan kebiasaan baik.",
          "Saya ingin memahami bagaimana nilai Islam membantu ketika saya sedang kecewa atau gagal.",
          "Saya merasa bersalah terhadap kesalahan masa lalu dan sulit memaafkan diri.",
          "Saya ingin menyeimbangkan belajar, ibadah, keluarga, dan waktu pribadi.",
          "Saya ingin memiliki lingkungan yang mendorong saya menjadi lebih baik.",
          "Saya ingin belajar membuat keputusan yang lebih jujur, amanah, dan bertanggung jawab.",
        ]) },
        { id: "values_q1", prompt: "Nilai yang paling ingin saya jaga dalam diri saya:", type: "textarea" },
        { id: "values_q2", prompt: "Kebiasaan baik yang ingin saya bangun:", type: "textarea" },
        { id: "values_q3", prompt: "Satu bentuk kebermanfaatan yang ingin saya lakukan untuk orang lain:", type: "textarea" },
      ],
    },
    {
      id: "safety",
      title: "7. Check-in Keamanan dan Kebutuhan Bantuan Segera",
      description: "Bagian ini membantu sekolah mengenali siswa yang membutuhkan dukungan lebih cepat. Jawaban perlu ditindaklanjuti secara rahasia dan sesuai prosedur perlindungan siswa.",
      items: [
        { id: "safe_home_school", prompt: "Saya merasa aman di rumah dan di sekolah.", type: "yes_no", options: [{...yesNo[0]}, {...yesNo[1], signal:{kind:"personal_safety",severity:"urgent",private:true}}], required: true, sensitive: true },
        { id: "no_threat", prompt: "Tidak ada orang yang sedang mengancam, memaksa, menyakiti, atau melecehkan saya.", type: "yes_no", options: [{...yesNo[0]}, {...yesNo[1], signal:{kind:"threat_or_abuse",severity:"urgent",private:true}}], required: true, sensitive: true },
        { id: "no_self_harm", prompt: "Saya tidak memiliki keinginan untuk menyakiti diri sendiri.", type: "yes_no", options: [{...yesNo[0]}, {...yesNo[1], signal:{kind:"self_harm_concern",severity:"urgent",private:true}}], required: true, sensitive: true },
        { id: "trusted_adult", prompt: "Saya memiliki setidaknya satu orang dewasa yang bisa saya hubungi saat keadaan terasa berat.", type: "yes_no", options: [{...yesNo[0]}, {...yesNo[1], signal:{kind:"support_gap",severity:"attention",private:true}}], required: true, sensitive: true },
        { id: "urgent_bk_request", prompt: "Saya ingin berbicara langsung dengan Guru BK secepatnya.", type: "yes_no", options: [{...yesNo[0], signal:{kind:"urgent_help_request",severity:"urgent",private:true}}, {...yesNo[1]}], required: true, sensitive: true },
      ],
    },
    {
      id: "priority",
      title: "8. Tentukan Prioritas Masalah",
      description: "Pilih maksimal tiga area yang paling membutuhkan bantuan terlebih dahulu.",
      items: [
        { id: "priority_areas", prompt: "Area yang paling membutuhkan bantuan", type: "multi", options: multi([
          "Kepercayaan diri / penerimaan diri",
          "Emosi / stres / kecemasan",
          "Kontrol diri / kebiasaan",
          "Masalah keluarga / rumah",
          "Pengambilan keputusan",
          "Tujuan pribadi / motivasi hidup",
          "Nilai diri / ibadah / keseimbangan",
        ]) },
        { id: "priority_other", prompt: "Lainnya", type: "text" },
        { id: "priority_1", prompt: "Prioritas 1", type: "text" },
        { id: "priority_2", prompt: "Prioritas 2", type: "text" },
        { id: "priority_3", prompt: "Prioritas 3", type: "text" },
      ],
    },
    {
      id: "deep_dive",
      title: "9. Pendalaman Masalah Prioritas",
      description: "Gunakan satu lembar untuk masalah yang paling penting saat ini.",
      items: [
        { id: "deep_main", prompt: "Masalah utama saya adalah:", type: "textarea", sensitive: true },
        { id: "deep_start", prompt: "Kapan masalah ini mulai terasa mengganggu?", type: "textarea", sensitive: true },
        { id: "deep_trigger", prompt: "Situasi/pemicu yang biasanya membuatnya lebih berat:", type: "textarea", sensitive: true },
        { id: "deep_thought", prompt: "Apa yang saya pikirkan ketika masalah muncul?", type: "textarea", sensitive: true },
        { id: "deep_feeling", prompt: "Apa yang saya rasakan?", type: "textarea", sensitive: true },
        { id: "deep_action", prompt: "Apa yang biasanya saya lakukan?", type: "textarea", sensitive: true },
        { id: "deep_impact", prompt: "Dampaknya terhadap belajar, ibadah, tidur, keluarga, atau relasi:", type: "textarea", sensitive: true },
        { id: "deep_tried", prompt: "Apa yang sudah saya coba untuk mengatasinya?", type: "textarea", sensitive: true },
        { id: "deep_helpful", prompt: "Apa yang sedikit membantu?", type: "textarea", sensitive: true },
        { id: "deep_worse", prompt: "Apa yang justru memperburuk?", type: "textarea", sensitive: true },
        { id: "deep_need", prompt: "Bantuan yang paling saya butuhkan saat ini:", type: "textarea", sensitive: true },
      ],
    },
    {
      id: "support",
      title: "10. Bentuk Bantuan yang Saya Butuhkan",
      items: [
        { id: "support_types", prompt: "Pilih bentuk bantuan yang Anda butuhkan.", type: "multi", options: multi([
          "Didengarkan tanpa langsung dinasihati.",
          "Dibantu memahami masalah dan pemicunya.",
          "Dibantu membuat langkah kecil yang realistis.",
          "Latihan mengelola emosi dan menenangkan diri.",
          "Latihan meningkatkan kepercayaan diri.",
          "Pendampingan memperbaiki kebiasaan dan disiplin.",
          "Dibantu berkomunikasi dengan orang tua/wali.",
          "Dibantu mengambil keputusan.",
          "Diarahkan kepada guru/ustadz/ustadzah yang relevan.",
          "Dirujuk kepada psikolog/profesional bila diperlukan.",
          "Saya belum tahu bantuan apa yang saya perlukan.",
        ]) },
      ],
    },
    {
      id: "trusted_person",
      title: "11. Siapa yang Paling Nyaman Saya Ajak Bicara?",
      items: [
        { id: "trusted_people", prompt: "Pilih satu atau lebih.", type: "multi", options: multi([
          "Guru BK", "Wali kelas", "Guru/ustadz/ustadzah tertentu", "Orang tua/wali", "Saudara dewasa", "Teman yang dapat dipercaya", "Psikolog/profesional", "Belum ada / saya belum tahu",
        ]) },
      ],
    },
    {
      id: "action_plan",
      title: "12. Personal Action Plan - 14 Hari",
      description: "Rencana bukan untuk menyelesaikan semua masalah sekaligus. Fokus pada satu perubahan kecil yang dapat dilakukan dan dievaluasi.",
      items: [
        { id: "plan_target", prompt: "Target kecil", type: "text" },
        { id: "plan_step", prompt: "Langkah", type: "textarea" },
        { id: "plan_support", prompt: "Dukungan", type: "text" },
        { id: "plan_review", prompt: "Waktu evaluasi", type: "text" },
        { id: "plan_commitment", prompt: "Satu kalimat komitmen saya untuk 14 hari ke depan:", type: "textarea" },
      ],
    },
    {
      id: "reflection_14d",
      title: "13. Refleksi Setelah 14 Hari",
      items: [
        { id: "reflection_success", prompt: "Perubahan kecil apa yang berhasil saya lakukan?", type: "textarea" },
        { id: "reflection_difficulty", prompt: "Apa yang masih terasa sulit?", type: "textarea" },
        { id: "reflection_learning", prompt: "Apa yang saya pelajari tentang diri saya?", type: "textarea" },
        { id: "reflection_more_help", prompt: "Apakah saya masih membutuhkan bantuan lanjutan? Mengapa?", type: "textarea" },
        { id: "reflection_next", prompt: "Langkah berikutnya yang ingin saya lakukan:", type: "textarea" },
      ],
    },
  ],
};
