"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, BriefcaseBusiness, ChevronRight, Compass, FolderCheck, Save, Search, Target } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { toUserMessage } from "@/lib/errors";

type SelfProfile={interests:string;strengths:string;values_work:string;abilities:string;work_environment_preferences:string;interaction_style:string;development_areas:string};
type Choice={id?:string;position:"A"|"B"|"C";custom_name:string;reason:string;review_date:string;status:string};
type Portfolio={id:string;title:string;category:string;evidence_url:string|null;reflection:string|null;occurred_at:string|null};
const EMPTY:SelfProfile={interests:"",strengths:"",values_work:"",abilities:"",work_environment_preferences:"",interaction_style:"",development_areas:""};
const blank=(position:"A"|"B"|"C"):Choice=>({position,custom_name:"",reason:"",review_date:"",status:"active"});

export default function StudentCareerPage(){
  const [studentId,setStudentId]=useState("");const [profile,setProfile]=useState<SelfProfile>(EMPTY);const [choices,setChoices]=useState<Choice[]>([blank("A"),blank("B"),blank("C")]);const [portfolio,setPortfolio]=useState<Portfolio[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
  useEffect(()=>{void load()},[]);
  async function load(){setLoading(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Silakan masuk terlebih dahulu.");const link=await supabase.from("student_auth_links").select("student_id").eq("auth_user_id",session.user.id).single();if(link.error)throw link.error;const id=link.data.student_id;setStudentId(id);const [p,c,f]=await Promise.all([supabase.from("career_self_profiles").select("interests,strengths,values_work,abilities,work_environment_preferences,interaction_style,development_areas").eq("student_id",id).maybeSingle(),supabase.from("student_career_choices").select("id,position,custom_name,reason,review_date,status").eq("student_id",id).in("position",["A","B","C"]),supabase.from("career_portfolio_items").select("id,title,category,evidence_url,reflection,occurred_at").eq("student_id",id).eq("status","active").order("occurred_at",{ascending:false})]);if(p.error||c.error||f.error)throw p.error||c.error||f.error;if(p.data)setProfile({...EMPTY,...p.data} as SelfProfile);const map=new Map((c.data??[]).map(x=>[x.position,x]));setChoices(["A","B","C"].map(pos=>{const x=map.get(pos);return x?{...x,custom_name:x.custom_name??"",reason:x.reason??"",review_date:x.review_date??""} as Choice:blank(pos as "A"|"B"|"C")}));setPortfolio((f.data??[]) as Portfolio[]);}catch(e){setMessage(toUserMessage(e));}finally{setLoading(false)}}
  async function saveSelf(){if(!studentId)return;setSaving(true);try{const {error}=await supabase.from("career_self_profiles").upsert({student_id:studentId,...profile,updated_at:new Date().toISOString()},{onConflict:"student_id"});if(error)throw error;setMessage("Profil Kenali Diriku berhasil disimpan.");}catch(e){setMessage(toUserMessage(e));}finally{setSaving(false)}}
  function updateChoice(position:string,patch:Partial<Choice>){setChoices(list=>list.map(x=>x.position===position?{...x,...patch}:x))}
  async function saveChoices(){setSaving(true);try{const rows=choices.filter(x=>x.custom_name.trim()).map(x=>({student_id:studentId,position:x.position,custom_name:x.custom_name.trim(),reason:x.reason||null,review_date:x.review_date||null,status:"active",updated_at:new Date().toISOString()}));if(rows.length){const {error}=await supabase.from("student_career_choices").upsert(rows,{onConflict:"student_id,position"});if(error)throw error;}setMessage("Plan A/B/C berhasil disimpan. Plan B dan C adalah alternatif yang tetap bermakna, bukan pilihan kalah.");}catch(e){setMessage(toUserMessage(e));}finally{setSaving(false)}}
  if(loading)return <main className="center-screen"><div className="loader"/></main>;
  return <main className="assessment-page"><section className="assessment-shell career-student-shell"><Link href="/student" className="back-link"><ArrowLeft size={17}/> Beranda siswa</Link><div className="assessment-title" style={{marginTop:22}}><p className="eyebrow">BK KARIER</p><h1>Perjalanan Karier Saya</h1><p>Kenali diri, eksplorasi profesi, bandingkan pilihan, susun Plan A/B/C, lalu ubah pilihan menjadi langkah yang dapat dijalankan.</p></div>{message&&<div className="workspace-message" style={{marginLeft:0,marginRight:0}}>{message}</div>}
    <div className="career-journey-strip">{[["1","Kenali Diri"],["2","Eksplorasi"],["3","Refleksi"],["4","Bandingkan"],["5","Rencanakan"],["6","Tindak Lanjut"]].map(([n,t])=><div key={n}><span>{n}</span><strong>{t}</strong></div>)}</div>
    <section className="assessment-section-card"><div className="assessment-section-head"><span><Compass size={18}/></span><div><h2>Kenali Diriku</h2><p>Minat, kekuatan, nilai hidup, kemampuan, preferensi lingkungan kerja, gaya interaksi, dan area pengembangan.</p></div></div><div className="career-self-grid"><Text label="Minat" value={profile.interests} onChange={v=>setProfile({...profile,interests:v})}/><Text label="Kekuatan" value={profile.strengths} onChange={v=>setProfile({...profile,strengths:v})}/><Text label="Nilai kerja yang penting" value={profile.values_work} onChange={v=>setProfile({...profile,values_work:v})}/><Text label="Kemampuan yang saya miliki" value={profile.abilities} onChange={v=>setProfile({...profile,abilities:v})}/><Text label="Preferensi lingkungan kerja" value={profile.work_environment_preferences} onChange={v=>setProfile({...profile,work_environment_preferences:v})}/><Text label="Gaya interaksi" value={profile.interaction_style} onChange={v=>setProfile({...profile,interaction_style:v})}/><Text label="Area yang ingin saya kembangkan" value={profile.development_areas} onChange={v=>setProfile({...profile,development_areas:v})}/></div><div className="assessment-actions"><button className="assessment-primary" onClick={saveSelf} disabled={saving}><Save size={16}/> Simpan Kenali Diriku</button></div></section>
    <div className="career-feature-grid"><Link href="/student/career/explore" className="career-feature-card"><Search size={22}/><div><span>CAREER 360°</span><h2>Eksplorasi Karier</h2><p>Cari profesi dan pelajari aktivitas nyata, kompetensi, jalur pendidikan, tantangan, kontribusi, risiko, dan alternatif.</p></div><ChevronRight size={18}/></Link><Link href="/student/action-plan" className="career-feature-card"><Target size={22}/><div><span>ROADMAP</span><h2>Action Plan</h2><p>Hubungkan keputusan karier dengan langkah 30 hari, semester, satu tahun, dan tindak lanjut.</p></div><ChevronRight size={18}/></Link></div>
    <section className="assessment-section-card"><div className="assessment-section-head"><span><BriefcaseBusiness size={18}/></span><div><h2>Plan A / B / C</h2><p>Plan B bukan pilihan kalah. Ia adalah desain ketahanan karier agar tujuan kontribusi tetap dapat dicapai walaupun jalur berubah.</p></div></div><div className="career-choice-list">{choices.map(choice=><div className="career-choice-card" key={choice.position}><div className="career-choice-label">PLAN {choice.position}</div><label><span>Pilihan yang ingin dieksplorasi</span><input value={choice.custom_name} onChange={e=>updateChoice(choice.position,{custom_name:e.target.value})} placeholder="Contoh: Dokter"/></label><label><span>Alasan saya</span><textarea rows={3} value={choice.reason} onChange={e=>updateChoice(choice.position,{reason:e.target.value})} placeholder="Mengapa pilihan ini ingin saya eksplorasi?"/></label><label><span>Tanggal review</span><input type="date" value={choice.review_date} onChange={e=>updateChoice(choice.position,{review_date:e.target.value})}/></label></div>)}</div><div className="assessment-actions"><button className="assessment-primary" onClick={saveChoices} disabled={saving}><Save size={16}/> Simpan Plan A/B/C</button></div></section>
    <section className="assessment-section-card"><div className="assessment-section-head"><span><FolderCheck size={18}/></span><div><h2>Portofolio Eksplorasi</h2><p>Proyek, prestasi, organisasi, volunteering, course, kompetisi, shadowing, atau bukti lain yang membantu menguji pilihan karier.</p></div></div>{portfolio.length?<div className="career-portfolio-list">{portfolio.map(item=><div key={item.id}><strong>{item.title}</strong><span>{item.category}{item.occurred_at?` · ${new Intl.DateTimeFormat("id-ID").format(new Date(item.occurred_at))}`:""}</span><p>{item.reflection||"Belum ada refleksi."}</p></div>)}</div>:<p className="empty-state">Belum ada bukti eksplorasi. Modul tambah portofolio akan muncul pada tahap berikutnya.</p>}</section>
  </section></main>
}
function Text({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><span>{label}</span><textarea rows={3} value={value} onChange={e=>onChange(e.target.value)}/></label>}
