"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, CalendarCheck, CheckCircle2, Save, Target } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { toUserMessage } from "@/lib/errors";
import { ErrorCard } from "@/components/common/ErrorCard";

type Plan={id:string;domain:string;goal:string;small_step:string|null;support:string|null;evidence:string|null;start_date:string;review_date:string|null;status:string;student_reflection:string|null;counselor_note:string|null;updated_at:string};
const DOMAIN:Record<string,string>={personal:"Pribadi",learning:"Belajar",social:"Sosial",career:"Karier"};

export default function StudentActionPlanPage(){
  const [plans,setPlans]=useState<Plan[]>([]);const [studentId,setStudentId]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState("");const [message,setMessage]=useState("");
  useEffect(()=>{void load()},[]);
  async function load(){setLoading(true);setMessage("");try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Silakan masuk terlebih dahulu.");const link=await supabase.from("student_auth_links").select("student_id").eq("auth_user_id",session.user.id).single();if(link.error)throw link.error;setStudentId(link.data.student_id);const res=await supabase.from("assessment_action_plans").select("id,domain,goal,small_step,support,evidence,start_date,review_date,status,student_reflection,counselor_note,updated_at").eq("student_id",link.data.student_id).order("updated_at",{ascending:false});if(res.error)throw res.error;setPlans((res.data??[]) as Plan[]);}catch(e){setMessage(toUserMessage(e));}finally{setLoading(false)}}
  function change(id:string,patch:Partial<Plan>){setPlans(list=>list.map(p=>p.id===id?{...p,...patch}:p))}
  async function save(plan:Plan){setSaving(plan.id);setMessage("");try{const {error}=await supabase.from("assessment_action_plans").update({student_reflection:plan.student_reflection||null,status:plan.status,updated_at:new Date().toISOString()}).eq("id",plan.id).eq("student_id",studentId);if(error)throw error;setMessage("Perkembangan rencana berhasil disimpan.");}catch(e){setMessage(toUserMessage(e));}finally{setSaving("")}}
  if(loading)return <main className="center-screen"><div className="loader"/></main>;
  return <main className="assessment-page"><section className="assessment-shell"><Link href="/student" className="back-link"><ArrowLeft size={17}/> Beranda siswa</Link><div className="assessment-title" style={{marginTop:22}}><p className="eyebrow">ACTION PLAN</p><h1>Rencana Perkembangan Saya</h1><p>Fokus pada langkah kecil yang realistis. Gunakan halaman ini untuk melihat rencana yang dibuat dari asesmen dan mencatat perkembangan.</p></div>{message&&<div className="workspace-message" style={{marginLeft:0,marginRight:0}}>{message}</div>}{!plans.length?<div className="assessment-section-card"><div className="viewer-empty"><Target size={38}/><strong>Belum ada Action Plan</strong><p>Action Plan akan muncul setelah Anda membuat rencana pada asesmen Pribadi, Belajar, Sosial, atau Karier.</p></div></div>:<div className="student-plan-list">{plans.map(plan=><article className="student-plan-card" key={plan.id}><div className="student-plan-head"><div><span>{DOMAIN[plan.domain]??plan.domain}</span><h2>{plan.goal}</h2></div><span className={`student-plan-status ${plan.status}`}>{plan.status==="completed"?"Selesai":plan.status==="active"?"Aktif":plan.status}</span></div><div className="student-plan-details"><Detail label="Langkah kecil" value={plan.small_step}/><Detail label="Dukungan" value={plan.support}/><Detail label="Bukti / komitmen" value={plan.evidence}/><Detail label="Evaluasi" value={plan.review_date?new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"long",year:"numeric"}).format(new Date(plan.review_date)):"Belum ditentukan"}/></div>{plan.counselor_note&&<div className="student-plan-note"><CalendarCheck size={17}/><div><strong>Catatan Guru BK</strong><p>{plan.counselor_note}</p></div></div>}<label className="profile-field"><span>Refleksi perkembangan saya</span><textarea rows={4} value={plan.student_reflection??""} onChange={e=>change(plan.id,{student_reflection:e.target.value})} placeholder="Apa yang sudah berjalan? Apa yang masih sulit?"/></label><div className="student-plan-actions"><button className="wide-secondary" onClick={()=>change(plan.id,{status:plan.status==="completed"?"active":"completed"})}>{plan.status==="completed"?"Aktifkan lagi":<><CheckCircle2 size={16}/> Tandai selesai</>}</button><button className="small-primary" onClick={()=>save(plan)} disabled={saving===plan.id}><Save size={16}/>{saving===plan.id?"Menyimpan...":"Simpan perkembangan"}</button></div></article>)}</div>}</section></main>
}
function Detail({label,value}:{label:string;value:string|null}){return <div><span>{label}</span><strong>{value||"—"}</strong></div>}
