"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { ArrowLeft, BookOpenCheck, CheckCircle2, Compass, Lightbulb, Route, ShieldCheck, Sparkles, Target, TriangleAlert, UsersRound } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { toUserMessage } from "@/lib/errors";

type Career={id:string;slug:string;name:string;category:string|null;aliases:string[];summary:string|null;activities:string|null;contribution:string|null;good_values:string|null;supporting_profile:string|null;competencies:string|null;education_path:string|null;challenges:string|null;difficulty_factors:string|null;risk_mitigation:string|null;prospects:string|null;alternatives:string|null;start_now:string|null;reflection_questions:unknown;last_reviewed_at:string|null;sources:unknown};

export default function CareerProfilePage(){
  const {slug}=useParams<{slug:string}>();const [career,setCareer]=useState<Career|null>(null);const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);const [saved,setSaved]=useState(false);
  useEffect(()=>{void load()},[slug]);
  async function load(){setLoading(true);try{const {data,error}=await supabase.from("career_profiles").select("*").eq("slug",slug).eq("is_published",true).single();if(error)throw error;setCareer(data as Career);}catch(e){setMessage(toUserMessage(e));}finally{setLoading(false)}}
  async function saveExplore(){if(!career)return;try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Silakan masuk terlebih dahulu.");const link=await supabase.from("student_auth_links").select("student_id").eq("auth_user_id",session.user.id).single();if(link.error)throw link.error;const {error}=await supabase.from("student_career_choices").upsert({student_id:link.data.student_id,career_profile_id:career.id,custom_name:career.name,position:"exploring",reason:"Sedang dipelajari melalui Career 360°",status:"active",updated_at:new Date().toISOString()},{onConflict:"student_id,position"});if(error)throw error;setSaved(true);setMessage("Karier ditambahkan ke eksplorasi Anda.");}catch(e){setMessage(toUserMessage(e))}}
  if(loading)return <main className="center-screen"><div className="loader"/></main>;
  if(!career)return <main className="assessment-page"><section className="assessment-shell"><Link href="/student/career/explore" className="back-link"><ArrowLeft size={17}/> Career Explorer</Link><div className="assessment-section-card" style={{marginTop:20}}><p>{message||"Profil karier belum tersedia."}</p></div></section></main>;
  const questions=Array.isArray(career.reflection_questions)?career.reflection_questions.filter(x=>typeof x==="string") as string[]:[];
  return <main className="assessment-page"><section className="assessment-shell career-student-shell"><Link href="/student/career/explore" className="back-link"><ArrowLeft size={17}/> Career Explorer</Link><div className="career-360-hero"><div><p className="eyebrow">CAREER 360° · {career.category||"KARIER"}</p><h1>{career.name}</h1>{career.aliases?.length>0&&<p className="career-aliases">{career.aliases.join(" · ")}</p>}<p>{career.summary}</p></div><button className={saved?"assessment-save":"assessment-primary"} onClick={saveExplore}><CheckCircle2 size={16}/>{saved?"Tersimpan":"Simpan untuk dieksplorasi"}</button></div>{message&&<div className="workspace-message" style={{marginLeft:0,marginRight:0}}>{message}</div>}<div className="career-360-grid"><Section icon={<Compass/>} title="Aktivitas & Realitas Kerja" text={career.activities}/><Section icon={<UsersRound/>} title="Kontribusi & Manfaat" text={career.contribution}/><Section icon={<Sparkles/>} title="Nilai Kebaikan / Integritas" text={career.good_values}/><Section icon={<ShieldCheck/>} title="Profil yang Mendukung" text={career.supporting_profile}/><Section icon={<Target/>} title="Kompetensi yang Dibutuhkan" text={career.competencies}/><Section icon={<BookOpenCheck/>} title="Jalur Pendidikan" text={career.education_path}/><Section icon={<TriangleAlert/>} title="Tantangan & Pengorbanan" text={career.challenges}/><Section icon={<TriangleAlert/>} title="Mengapa Seseorang Bisa Kesulitan?" text={career.difficulty_factors}/><Section icon={<ShieldCheck/>} title="Cara Mengurangi Risiko" text={career.risk_mitigation}/><Section icon={<Route/>} title="Prospek & Perkembangan" text={career.prospects}/><Section icon={<Compass/>} title="Alternatif Karier" text={career.alternatives}/><Section icon={<Lightbulb/>} title="Mulai dari Sekarang" text={career.start_now}/></div>{questions.length>0&&<section className="assessment-section-card career-reflection-box"><div className="assessment-section-head"><span><Lightbulb size={18}/></span><div><h2>Refleksi Kecocokan</h2><p>Gunakan pertanyaan ini untuk menentukan apakah profesi perlu dieksplorasi lebih jauh—bukan sebagai vonis cocok/tidak cocok.</p></div></div><div>{questions.map((q,i)=><p key={q}><strong>{i+1}.</strong> {q}</p>)}</div></section>}<div className="career-source-note"><span>Terakhir ditinjau</span><strong>{career.last_reviewed_at?new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"long",year:"numeric"}).format(new Date(career.last_reviewed_at)):"Belum dicatat"}</strong><p>Informasi jalur pendidikan, regulasi, biaya, dan prospek perlu selalu diperiksa kembali pada sumber resmi terbaru sebelum mengambil keputusan.</p></div></section></main>
}
function Section({icon,title,text}:{icon:React.ReactNode;title:string;text:string|null}){return <article className="career-360-section"><div>{icon}<h2>{title}</h2></div><p>{text||"Konten ini sedang dilengkapi oleh tim BK."}</p></article>}
