"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, ExternalLink, GitCompareArrows, Save, Search } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { toUserMessage } from "@/lib/errors";
import { comparisonIsReady, toggleComparisonSelection } from "@/lib/career-planning";

type Career = { id:string; slug:string; name:string; category:string|null; summary:string|null; activities:string|null; competencies:string|null; education_path:string|null; challenges:string|null; contribution:string|null; prospects:string|null; risk_mitigation:string|null; start_now:string|null };

export default function CareerComparePage(){
  const [studentId,setStudentId]=useState("");
  const [careers,setCareers]=useState<Career[]>([]);
  const [selected,setSelected]=useState<string[]>([]);
  const [reflections,setReflections]=useState<Record<string,string>>({});
  const [query,setQuery]=useState("");
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const [message,setMessage]=useState("");
  useEffect(()=>{void load()},[]);
  async function load(){setLoading(true);setMessage("");try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Silakan masuk terlebih dahulu.");const [linkRes,careerRes]=await Promise.all([supabase.from("student_auth_links").select("student_id").eq("auth_user_id",session.user.id).single(),supabase.from("career_profiles").select("id,slug,name,category,summary,activities,competencies,education_path,challenges,contribution,prospects,risk_mitigation,start_now").eq("is_published",true).order("name")]);if(linkRes.error||careerRes.error)throw linkRes.error||careerRes.error;setStudentId(linkRes.data.student_id);setCareers((careerRes.data??[]) as Career[]);}catch(error){setMessage(toUserMessage(error));}finally{setLoading(false)}}
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return careers.filter(c=>!q||[c.name,c.category,c.summary].some(v=>v?.toLowerCase().includes(q)))},[careers,query]);
  const chosen=selected.map(id=>careers.find(c=>c.id===id)).filter(Boolean) as Career[];
  function toggle(id:string){const next=toggleComparisonSelection(selected,id);if(next===selected&&!selected.includes(id)&&selected.length>=4)setMessage("Maksimal 4 karier dalam satu perbandingan.");else setMessage("");setSelected(next)}
  async function saveComparison(){if(!studentId||!comparisonIsReady(selected))return;setSaving(true);setMessage("");let comparisonId="";try{const {data,error}=await supabase.from("career_comparisons").insert({student_id:studentId,title:`Perbandingan ${chosen.map(x=>x.name).join(" · ")}`}).select("id").single();if(error)throw error;comparisonId=data.id;const rows=chosen.map((career,index)=>({comparison_id:comparisonId,career_profile_id:career.id,custom_name:career.name,student_reflection:{note:(reflections[career.id]??"").trim()},sort_order:index}));const inserted=await supabase.from("career_comparison_items").insert(rows);if(inserted.error)throw inserted.error;setMessage("Perbandingan berhasil disimpan. Gunakan sebagai bahan refleksi dan diskusi, bukan untuk menentukan pemenang.");}catch(error){if(comparisonId)await supabase.from("career_comparisons").delete().eq("id",comparisonId);setMessage(toUserMessage(error));}finally{setSaving(false)}}
  if(loading)return <main className="center-screen"><div className="loader"/></main>;
  return <main className="assessment-page"><section className="assessment-shell career-student-shell"><Link href="/student/career" className="back-link"><ArrowLeft size={17}/> Perjalanan Karier</Link><div className="assessment-title" style={{marginTop:22}}><p className="eyebrow">BANDINGKAN PILIHAN</p><h1>Bandingkan 2–4 Karier</h1><p>Lihat perbedaan realitas kerja, kompetensi, jalur pendidikan, tantangan, kontribusi, dan langkah awal. Tidak ada skor atau “karier terbaik”.</p></div>{message&&<div className="workspace-message" style={{marginLeft:0,marginRight:0}}>{message}</div>}<section className="assessment-section-card"><div className="career-compare-toolbar"><div className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari profesi atau bidang..."/></div><div className="compare-count"><strong>{selected.length}/4</strong><span>dipilih</span></div></div><div className="career-select-grid">{filtered.map(c=><button key={c.id} type="button" className={selected.includes(c.id)?"career-select-card selected":"career-select-card"} onClick={()=>toggle(c.id)}><span className="career-select-check">{selected.includes(c.id)&&<Check size={14}/>}</span><div><small>{c.category||"Bidang karier"}</small><strong>{c.name}</strong><p>{c.summary||"Buka Career 360° untuk informasi lengkap."}</p></div></button>)}</div></section>{chosen.length>0&&<section className="assessment-section-card"><div className="assessment-section-head"><span><GitCompareArrows size={18}/></span><div><h2>Ruang Perbandingan</h2><p>Pilih minimal dua karier. Catat hal yang ingin Anda diskusikan dengan Guru BK pada masing-masing pilihan.</p></div></div><div className="career-compare-grid">{chosen.map(c=><article className="career-compare-column" key={c.id}><div className="career-compare-head"><div><small>{c.category||"Karier"}</small><h3>{c.name}</h3></div><Link href={`/student/career/explore/${c.slug}`} title="Buka Career 360°"><ExternalLink size={17}/></Link></div><CompareRow label="Aktivitas nyata" value={c.activities}/><CompareRow label="Kompetensi" value={c.competencies}/><CompareRow label="Jalur pendidikan" value={c.education_path}/><CompareRow label="Tantangan" value={c.challenges}/><CompareRow label="Kontribusi" value={c.contribution}/><CompareRow label="Prospek" value={c.prospects}/><CompareRow label="Mitigasi risiko" value={c.risk_mitigation}/><CompareRow label="Mulai sekarang" value={c.start_now}/><label className="career-reflection-field"><span>Refleksi saya</span><textarea rows={4} value={reflections[c.id]??""} onChange={e=>setReflections({...reflections,[c.id]:e.target.value})} placeholder="Apa yang menarik, meragukan, atau perlu saya tanyakan?"/></label></article>)}</div><div className="assessment-actions"><button className="assessment-primary" disabled={!comparisonIsReady(selected)||saving} onClick={saveComparison}><Save size={16}/>{saving?"Menyimpan...":"Simpan Perbandingan"}</button></div></section>}</section></main>;
}
function CompareRow({label,value}:{label:string;value:string|null}){return <div className="career-compare-row"><span>{label}</span><p>{value||"Belum ada informasi terkurasi."}</p></div>}
